### ISSUE TITLE
StackOverflow Fehler bei der Umwandlung zum JSON

### ISSUE THREAD

**Issue by Glaeydar** [Glaeydar/Projekt-Car-Sharing-Management#125]
**Beschreibung des Fehlers**
Bei der Umwandlung in ein JSON tretten StackOverflow Fehler auf.
Dies passiert mit vielen Objekten. Liste folgt.

**Schritte um den Fehler zu Reproduzieren**
Account a = AccountService.getAccountById(1);
String s = new Gson().toJson(a); ⚡
System.out.println(s);

-> Fehler tritt auf

**Erwartetes Verhalten**
Der Account als JSON

**Zusätzliche Information**
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.google.gson.Gson.getAdapter(Gson.java:434)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:100)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)

**Comment by Glaeydar** [comment]
- Account
- Bill
- Car
- ChargeStation 
- Reservation
- Trip

**Comment by Glaeydar** [comment]
5c6fdba5b99b65d347776f1a942dfd829ca71d84
